name: PocketGymTrainer
description: A mobile app to help structure your workouts.

publish_to: 'none'


version: 0.1.0+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.4.5
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  image_picker: '0.8.6'
  http: ^0.13.5
  uuid: ^3.0.6
  flutter_slidable: any
  go_router: ^7.1.1
  sidebarx: ^0.15.0
  carousel_slider: ^4.2.1
  fl_chart: ^0.62.0
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.2
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.2
  stop_watch_timer: ^2.0.0
  intl: any
  auto_size_text: ^3.0.0
  autocomplete_textfield: ^2.0.1
  scrollable_positioned_list: ^0.3.8
  grouped_list: ^5.1.2
  multi_select_flutter: ^4.1.3
  url_launcher: ^6.1.13
  number_paginator: ^0.4.0
  animated_snack_bar: ^0.4.0
  dropdown_button2: ^2.3.9
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/bodybuilder.png
    - images/exercise.png
    - images/push-up.png
    - images/icon.png
  fonts:
  - family: DigitalDisplay
    fonts:
      - asset: fonts/DigitalDisplayRegular-ODEO.ttf

