name: PocketGymTrainer
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: '0.8.6'
  http: ^0.13.5
  uuid: ^3.0.6
  flutter_slidable: any
  go_router: ^7.1.1
  sidebarx: ^0.15.0
  carousel_slider: ^4.2.1
  fl_chart: ^0.62.0
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.2
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.2
  stop_watch_timer: ^2.0.0
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  autocomplete_textfield: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/bodybuilder.png
    - images/exercise.png
    - images/push-up.png
  fonts:
  - family: DigitalDisplay
    fonts:
      - asset: fonts/DigitalDisplayRegular-ODEO.ttf

